# render.yaml (Corrected Order, Direct fromService links)

# Define Databases FIRST
databases:
  - name: blueprint-redis # Matches name used in fromService
    plan: free
    databaseName: blueprint_parser_redis # Optional internal name
    ipAllowList: [] # Allows Render services in the same account

# Define Services AFTER Databases
services:
  # Web Service (Flask/Gunicorn)
  - type: web
    name: blueprint-parser-web
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: "3.12"
      - key: FLASK_APP
        value: "wsgi:application"
      - key: FLASK_ENV
        value: "production"
      - key: SECRET_KEY
        generateValue: true
      # Direct links to Redis defined above
      - key: REDIS_URL
        fromService:
          type: redis
          name: blueprint-redis
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: blueprint-redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: redis
          name: blueprint-redis
          property: connectionString
      # --- R2/S3 Config (Secrets set via UI) ---
      - key: R2_ENDPOINT_URL
        value: "https://0948134cfe20aade9cfc72f11f995766.r2.cloudflarestorage.com"
      - key: R2_BUCKET_NAME
        value: "blueprint-parser-uploads"
      # R2 Keys are set manually in Render UI Environment Variables

  # Worker Service (Celery)
  - type: worker
    name: blueprint-parser-worker
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A celery_app.celery worker --loglevel=info -c 1"
    envVars:
      - key: PYTHON_VERSION
        value: "3.12"
      - key: FLASK_ENV
        value: "production"
      # Direct links to Redis defined above
      - key: REDIS_URL
        fromService:
          type: redis
          name: blueprint-redis
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: blueprint-redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: redis
          name: blueprint-redis
          property: connectionString
      # --- R2/S3 Config (Secrets set via UI) ---
      - key: R2_ENDPOINT_URL
        value: "https://0948134cfe20aade9cfc72f11f995766.r2.cloudflarestorage.com"
      - key: R2_BUCKET_NAME
        value: "blueprint-parser-uploads"
      # R2 Keys are set manually in Render UI Environment Variables