# render.yaml (Corrected Version)

services:
  # Web Service (Flask/Gunicorn)
  - type: web
    name: blueprint-parser-web # You can rename this during Blueprint setup if desired
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: "3.12"
      - key: FLASK_APP
        value: "wsgi:application"
      - key: FLASK_ENV
        value: "production"
      - key: SECRET_KEY
        generateValue: true
      - key: REDIS_URL
        fromService:
          type: redis
          name: blueprint-redis # Matches database name below
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: blueprint-redis
          property: connectionString # Append /1 in code or UI if needed
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: redis
          name: blueprint-redis
          property: connectionString # Append /2 in code or UI if needed
      # --- R2/S3 Config ---
      - key: R2_ENDPOINT_URL
        value: "https://0948134cfe20aade9cfc72f11f995766.r2.cloudflarestorage.com" # CORRECTED: Your specific global endpoint
      - key: R2_BUCKET_NAME
        value: "blueprint-parser-uploads"
      - key: R2_ACCESS_KEY_ID
        fromSecretFile:
          name: r2-credentials # Name of the Secret File in Render UI
          key: R2_ACCESS_KEY_ID # Key *inside* the Secret File content
      - key: R2_SECRET_ACCESS_KEY
        fromSecretFile:
          name: r2-credentials # Name of the Secret File in Render UI
          key: R2_SECRET_ACCESS_KEY # Key *inside* the Secret File content
      # - key: MAX_CONTENT_SIZE # Optional
      #   value: "104857600"

  # Worker Service (Celery)
  - type: worker
    name: blueprint-parser-worker
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A celery_app.celery worker --loglevel=info -c 1"
    envVars:
      - key: PYTHON_VERSION
        value: "3.12"
      - key: FLASK_ENV
        value: "production"
      - key: REDIS_URL
        fromService:
          type: redis
          name: blueprint-redis # Matches database name below
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: blueprint-redis
          property: connectionString # Append /1 in code or UI if needed
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: redis
          name: blueprint-redis
          property: connectionString # Append /2 in code or UI if needed
      # --- R2/S3 Config ---
      - key: R2_ENDPOINT_URL
        value: "https://0948134cfe20aade9cfc72f11f995766.r2.cloudflarestorage.com" # Use the GLOBAL endpoint
      - key: R2_BUCKET_NAME
        value: "blueprint-parser-uploads"
      - key: R2_ACCESS_KEY_ID
        fromSecretFile:
          name: r2-credentials # Name of the Secret File in Render UI
          key: R2_ACCESS_KEY_ID # Key *inside* the Secret File content
      - key: R2_SECRET_ACCESS_KEY
        fromSecretFile:
          name: r2-credentials # Name of the Secret File in Render UI
          key: R2_SECRET_ACCESS_KEY # Key *inside* the Secret File content

# Redis Instance (Managed by Render)
databases:
  - name: blueprint-redis # Matches name used in fromService
    plan: free
    databaseName: blueprint_parser_redis # Optional internal name
    ipAllowList: [] # Allows Render services in the same account