# render.yaml (Temporarily Removing fromService Links)

# Define Databases FIRST
databases:
  - name: blueprint-redis
    plan: free
    databaseName: blueprint_parser_redis
    ipAllowList: []

# Define Services AFTER Databases
services:
  # Web Service (Flask/Gunicorn)
  - type: web
    name: blueprint-parser-web
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn wsgi:application"
    envVars:
      # --- REDIS URLs REMOVED - Will be added manually via UI ---
      - key: PYTHON_VERSION
        value: "3.12"
      - key: FLASK_APP
        value: "wsgi:application"
      - key: FLASK_ENV
        value: "production"
      - key: SECRET_KEY
        generateValue: true
      # --- R2/S3 Config (Secrets set via UI) ---
      - key: R2_ENDPOINT_URL
        value: "https://0948134cfe20aade9cfc72f11f995766.r2.cloudflarestorage.com"
      - key: R2_BUCKET_NAME
        value: "blueprint-parser-uploads"
      # R2 Keys are set manually in Render UI Environment Variables

  # Worker Service (Celery)
  - type: worker
    name: blueprint-parser-worker
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A celery_app.celery worker --loglevel=info -c 1"
    envVars:
      # --- REDIS URLs REMOVED - Will be added manually via UI ---
      - key: PYTHON_VERSION
        value: "3.12"
      - key: FLASK_ENV
        value: "production"
      # --- R2/S3 Config (Secrets set via UI) ---
      - key: R2_ENDPOINT_URL
        value: "https://0948134cfe20aade9cfc72f11f995766.r2.cloudflarestorage.com"
      - key: R2_BUCKET_NAME
        value: "blueprint-parser-uploads"
      # R2 Keys are set manually in Render UI Environment Variables